services:
  audio-qc:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: jy-algorithm-app-audio-qc:v1.0.0-cuda-amd64
    container_name: audio-qc-obfuscated
    ports:
      - "8090:8090"
    volumes:
      - /root/config/config_audio_qc.toml:/srv/app/config.toml:ro
    restart: unless-stopped
    # 如需让容器访问 GPU，取消下一行注释，并确保配置文件中 device = "cuda:0"。
    # gpus: all
